export const FETCH_THUMBNAILS = 'FETCH_THUMBNAILS';
export const FETCH_THUMBNAILS_FULFILLED = 'FETCH_THUMBNAILS_FULFILLED';
export const FETCH_PHOTO_INFO = 'FETCH_PHOTO_INFO';
export const FETCH_PHOTO_INFO_FULFILLED = 'FETCH_PHOTO_INFO_FULFILLED';
